### ISSUE TITLE
SelectQuery isn't compatible with PromiseLike?

### ISSUE THREAD

**Issue by cakoose** [Ff00ff/mammoth#220] opened 2021-02-10 22:58 UTC
```ts
declare function acceptPromiseLike<T>(promise: PromiseLike<T>): void;
...
const query = db.select(db.foo.id).from(db.foo);
await acceptPromiseLike(query); // error
```

Full error message:
```
Argument of type 'SelectQuery<{ id: Column<"id", "foo", string, false, false, undefined>; }, false>' is not assignable to parameter of type 'PromiseLike<{ id: string | undefined; }[]>'.
  Types of property 'then' are incompatible.
    Types of parameters 'onRejected' and 'onrejected' are incompatible.
      Type 'TResult2 | PromiseLike<TResult2>' is not assignable to type 'void | PromiseLike<void>'.
        Type 'TResult2' is not assignable to type 'void | PromiseLike<void>'.
          Type 'TResult2' is not assignable to type 'PromiseLike<void>'.

     await acceptPromiseLike(query); // error
                             ~~~~~
```

Is this mismatch accidental?

**Comment by martijndeh** [comment] 2021-02-11 11:20
Yes. It would be nice for those queries to actually to call `implements PromiseLike<..>` so it's compatibility is actually enforced. Does this only happen for the select query or also delete/insert/update queries?

**Comment by cakoose** [comment] 2021-02-16 09:05
Looks like it happens in all cases.  I get "not assignable to type PromiseLike" errors on all these lines:

```ts
    acceptPromiseLike(db.select(db.foo.id).from(db.foo));
    acceptPromiseLike(db.select(db.foo.id).from(db.foo).where(db.foo.id.eq('1')));
    acceptPromiseLike(db.update(db.foo).set({id: '1'}));
    acceptPromiseLike(db.update(db.foo).set({id: '1'}).where(db.foo.id.eq('1')));
    acceptPromiseLike(db.deleteFrom(db.foo));
    acceptPromiseLike(db.insertInto(db.foo).values({id: '1'}));
```

**Comment by martijndeh** [comment] 2021-08-03 07:57
It looks like this is fixed already — or I cannot reproduce it. See https://codesandbox.io/s/ecstatic-archimedes-pnbsk?file=/src/index.ts.

In any case I'm closing this issue assuming it's fixed. Please let me know if you can create a reproducible sandbox.

**Closed by martijndeh** 2021-08-03 07:57 UTC

**Comment by martijndeh** [comment] 2021-08-03 17:13
Good to hear, thanks.
