### ISSUE TITLE
The return type of (select|insert etc.).then is inferred as Promise<any>

### ISSUE THREAD

**Issue by frabbit** [Ff00ff/mammoth#175] opened 2020-11-23 10:01 UTC
...which kind of defeats the purpose of typed queries :D.

**Comment by martijndeh** [comment] 2020-11-23 10:18
Can you give me some more info please?

It's sometimes possible for return types to become `any` within Mammoth, but there should be plenty of checks (type tests) covering this.

It's also possible because of misconfiguration in your project e.g. not having tsconfig.json setup correctly, or having an error in one of your tables, which causes an `any` down the line when executing a query.

**Comment by frabbit** [comment] 2020-11-23 10:21
see: https://github.com/Ff00ff/mammoth/blob/master/src/select.ts#L99

The return type of then is inferred from the onFullfilled function i guess.

**Comment by frabbit** [comment] 2020-11-23 10:22
i guess any should be a type parameter there

**Comment by martijndeh** [comment] 2020-11-23 10:56
Ah right, yes, this needs to be improved. So just to get the whole situation here, you're probably doing something like this?

```
execSelectQuery().then((rows) => {
  // at this stage rows is typed correctly
  return 123;
}).then((result) => {
  // and here result is any instead of the proper return type of the onFulfilled
});

**Comment by frabbit** [comment] 2020-11-23 11:01
yes, and i have the same problem with async/await:

```
const x = await db
      .insertInto(db.question)
      .values({
        text,
        questionerId
      })
      .returning("id");
    return x; // x is typed as any here
```

**Comment by martijndeh** [comment] 2020-11-23 11:12
OK, I'll get the `then()` bit fixed.

The async/await case seems different though. Can you share some more info there? Or double-check if there is no error in your question table or somewhere else in your db instance.

**Comment by frabbit** [comment] 2020-11-23 11:23
Hi, it might be be related to `returning`, let me know if i'm doing something wrong here:

```javascript
import * as mam from "@ff00ff/mammoth";

const check = async () => {
  const question = mam.defineTable({
    id: mam.uuid().primaryKey().default(`gen_random_uuid()`),
    text: mam.text().notNull(),
  });

  const db1 = defineDb({ question }, undefined as any); // queryExecutor is not relevant for typing

  const res = await db1.insertInto(db1.question).values({
    text: "hello"
  }).returning("id");

  return res; // typed as any
}
```

**Comment by frabbit** [comment] 2020-11-23 11:34
I might have messed up my project settings. Let me double check because vs-code tells me otherwise than my local tsc.

**Comment by frabbit** [comment] 2020-11-23 11:45
ok, i figured out that my ide used typescript 4.0.2. Using 4.1.2 seems to fix this problem. Sorry for the trouble.

**Comment by martijndeh** [comment] 2020-11-23 11:55
No problem. The `then()` case is a nice report that needs fixing anyway, thanks. 👍

**Comment by frabbit** [comment] 2020-11-23 12:02
Ah i understand, so async/await infers the resulting type from the onfulfilled parameter ;). Good to know.

Something else, the type definition of `onrejected` needs to fixed too, void is wrong here. See the typescript promise definition here:

```typescript
/**
 * Represents the completion of an asynchronous operation
 */
interface Promise<T> {
    /**
     * Attaches callbacks for the resolution and/or rejection of the Promise.
     * @param onfulfilled The callback to execute when the Promise is resolved.
     * @param onrejected The callback to execute when the Promise is rejected.
     * @returns A Promise for the completion of which ever callback is executed.
     */
    then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): Promise<TResult1 | TResult2>;

    /**
     * Attaches a callback for only the rejection of the Promise.
     * @param onrejected The callback to execute when the Promise is rejected.
     * @returns A Promise for the completion of the callback.
     */
    catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): Promise<T | TResult>;
}
```

**Comment by frabbit** [comment] 2020-11-23 12:31
or to be more precise, all query types should be compatible with the \`PromiseLike\` interface:

```

interface PromiseLike<T> {
    /**
     * Attaches callbacks for the resolution and/or rejection of the Promise.
     * @param onfulfilled The callback to execute when the Promise is resolved.
     * @param onrejected The callback to execute when the Promise is rejected.
     * @returns A Promise for the completion of which ever callback is executed.
     */
    then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): PromiseLike<TResult1 | TResult2>;
}
```

**Comment by martijndeh** [comment] 2020-11-23 19:37
Yes, this is clear. You seem to have thought this through. Do you want to fix this yourself and adding a quick check (type test) or two? :)

**Comment by frabbit** [comment] 2020-11-24 09:39
Yes, i can try ;). Are there any existing type tests?

**Comment by martijndeh** [comment] 2020-11-24 18:09
Great! Yes, they are in the \_\_checks__ directory. Mammoth uses dts-jest https://www.npmjs.com/package/dts-jest to snapshot type definitions. This is key to avoid regressions on the public types because it’s so easy to turn everything in any. 😅

**Comment by martijndeh** [comment] 2020-11-26 06:27
How is it going? Do you want me to have a look with you?

**Comment by frabbit** [comment] 2020-11-26 12:18
Hey, didn't found the time to start yet. I hope to find some time next week.

**Comment by martijndeh** [comment] 2020-12-29 10:50
That's fine. I'm assuming you don't have the time anymore so I'll let someone else pick this one up. Let me know if you already started on this; then it's all yours of course. ;-)

**Comment by martijndeh** [comment] 2020-12-30 15:50
This should be fixed in the latest master. This is not published to npm yet.

**Closed by martijndeh** 2020-12-30 15:50 UTC

**Comment by frabbit** [comment] 2021-01-04 06:55
@martijndeh thx a lot, i'm sorry that i didn't found the time.

**Comment by martijndeh** [comment] 2021-01-04 09:53
No worries, maybe next time!
